### ISSUE TITLE
Cannot modify header information error on install

### ISSUE THREAD

**Issue by rxvl-d** [yasbil/yasbil#16]
Hi Nilavra,

Thank you so much for releasing this extension. It could be very useful for my work. I'm trying to get it intstalled to test it out at the moment and am running into an error.

Just after installing the wordpress plugin on a clean dockerized wordpress installation (version 6.2.2) I get this error when navigating to the YASBIL WP tab:

```
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-admin/includes/template.php:2546) in /var/www/html/wp-includes/pluggable.php on line 1421 Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/wp-admin/includes/template.php:2546) in /var/www/html/wp-includes/pluggable.php on line 1424
```

Nothing else shows up on the page. Not sure where to start with debugging this. Let me know if you have any ideas. Happy to share logs and such.

You should be able to reproduce this using this docker compse and installing `yasbil-wp-2.1.1.zip`

```
services:
   db:
     image: mysql:latest
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DEBUG: 1
       WP_ENVIRONMENT_TYPE: development
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress

volumes:
    db_data: {}
```

Best,

- Ratan Sebastian
